// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Store;

#nullable disable

namespace Store.Migrations.Migrations
{
    [DbContext(typeof(ResourceContext))]
    [Migration("20231209203754_Add_initial_data")]
    partial class Add_initial_data
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Store.Entities.OrderItemRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("OrderId")
                        .IsRequired()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems", (string)null);
                });

            modelBuilder.Entity("Store.Entities.OrderRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("date");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<Guid?>("ProviderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ProviderId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ProviderId");

                    b.HasIndex("ProviderId1");

                    b.HasIndex("OrderNumber", "ProviderId")
                        .IsUnique()
                        .HasDatabaseName("IX_Orders_Number_ProviderId")
                        .HasFilter("[ProviderId] IS NOT NULL");

                    b.ToTable("Orders", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e7f3b81c-ad30-4ab7-950a-3bf80f2448a5"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3319),
                            OrderNumber = "Order number 1",
                            ProviderId = new Guid("31148c84-057b-4de3-b1f9-31437bb57605")
                        },
                        new
                        {
                            Id = new Guid("11ddf150-41ce-4b2d-9b4e-8879ddd985de"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3356),
                            OrderNumber = "Order number 2",
                            ProviderId = new Guid("59f6586a-3f3d-44fb-a34e-f77024371f84")
                        },
                        new
                        {
                            Id = new Guid("33f56b0c-8f70-48b3-af46-c586177024d5"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3359),
                            OrderNumber = "Order number 3",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("06548f64-39a3-4bf8-9d96-4fee910d92d8"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3365),
                            OrderNumber = "Order number 4",
                            ProviderId = new Guid("59f6586a-3f3d-44fb-a34e-f77024371f84")
                        },
                        new
                        {
                            Id = new Guid("fa21ca76-5238-432a-8bb8-da05a2a844e9"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3367),
                            OrderNumber = "Order number 5",
                            ProviderId = new Guid("31148c84-057b-4de3-b1f9-31437bb57605")
                        },
                        new
                        {
                            Id = new Guid("c0777ac6-d5d3-4337-9deb-e2151f0f018d"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3370),
                            OrderNumber = "Order number 6",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("88410a8f-93d3-4f83-8a6c-08cb78687af9"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3372),
                            OrderNumber = "Order number 7",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("edcbfcb3-c99b-40fc-8ee9-a6e6ede61a2a"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3374),
                            OrderNumber = "Order number 8",
                            ProviderId = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5")
                        },
                        new
                        {
                            Id = new Guid("68d42dfc-c9ce-4363-bb96-302f41530da0"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3376),
                            OrderNumber = "Order number 9",
                            ProviderId = new Guid("59f6586a-3f3d-44fb-a34e-f77024371f84")
                        },
                        new
                        {
                            Id = new Guid("2faa13ff-a815-45ae-97f6-17d21e9e445f"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3379),
                            OrderNumber = "Order number 10",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("bdb4d7eb-d69b-4eaf-a8ac-c0307abafff7"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3380),
                            OrderNumber = "Order number 11",
                            ProviderId = new Guid("31148c84-057b-4de3-b1f9-31437bb57605")
                        },
                        new
                        {
                            Id = new Guid("d8b93273-654d-4f05-9e62-b7875af25dcb"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3384),
                            OrderNumber = "Order number 12",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("0376227e-2ea7-4dc2-aba5-3899b453e313"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3410),
                            OrderNumber = "Order number 13",
                            ProviderId = new Guid("abf69a2d-f358-48be-9b84-717b53df248c")
                        },
                        new
                        {
                            Id = new Guid("22cbeb59-4e82-4f49-9b08-28bb58766cbb"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3412),
                            OrderNumber = "Order number 14",
                            ProviderId = new Guid("59f6586a-3f3d-44fb-a34e-f77024371f84")
                        },
                        new
                        {
                            Id = new Guid("9cacc8bc-d1bb-43f4-a0f4-71e453692ffe"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3414),
                            OrderNumber = "Order number 15",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("6b10a57f-040a-4c3d-a565-418535b93ae4"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3415),
                            OrderNumber = "Order number 16",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("a760de11-89d4-425a-91ce-d4a8e7ba34d4"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3417),
                            OrderNumber = "Order number 17",
                            ProviderId = new Guid("b84f0c12-b6e5-4f16-a09a-6197dfd1f55c")
                        },
                        new
                        {
                            Id = new Guid("7396ac0e-e7ac-4c12-a305-a716795a036d"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3420),
                            OrderNumber = "Order number 18",
                            ProviderId = new Guid("b84f0c12-b6e5-4f16-a09a-6197dfd1f55c")
                        },
                        new
                        {
                            Id = new Guid("e33f53ff-cc79-4dd2-88b0-619cb8a2b407"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3422),
                            OrderNumber = "Order number 19",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("27f224c3-4c61-410c-a1cb-050635fd634e"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3425),
                            OrderNumber = "Order number 20",
                            ProviderId = new Guid("31148c84-057b-4de3-b1f9-31437bb57605")
                        },
                        new
                        {
                            Id = new Guid("8dc7aa4a-e666-442d-94d0-eb53efde6778"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3427),
                            OrderNumber = "Order number 21",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("95857335-f7c9-4ad8-b3bd-54af06d898ad"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3428),
                            OrderNumber = "Order number 22",
                            ProviderId = new Guid("b84f0c12-b6e5-4f16-a09a-6197dfd1f55c")
                        },
                        new
                        {
                            Id = new Guid("5b398dd2-652a-4a2d-9cad-ac8f1af0df46"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3431),
                            OrderNumber = "Order number 23",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("b1ed5375-e7b7-48c5-9246-17abac8873b0"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3432),
                            OrderNumber = "Order number 24",
                            ProviderId = new Guid("59f6586a-3f3d-44fb-a34e-f77024371f84")
                        },
                        new
                        {
                            Id = new Guid("d90e9a82-fdb0-408e-94c9-db5c40792d69"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3434),
                            OrderNumber = "Order number 25",
                            ProviderId = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5")
                        },
                        new
                        {
                            Id = new Guid("9e609923-0659-4c40-b30d-b065ae10005c"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3437),
                            OrderNumber = "Order number 26",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("e44844c8-429f-4597-855c-9b20f1ed8b44"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3438),
                            OrderNumber = "Order number 27",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("888202ab-ea3c-4785-a861-871ccca2f88f"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3441),
                            OrderNumber = "Order number 28",
                            ProviderId = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5")
                        },
                        new
                        {
                            Id = new Guid("62dee05c-9282-4ef6-a1ad-6cfb648719b0"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3443),
                            OrderNumber = "Order number 29",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("ae68103f-a8d3-4f8f-91e1-63c6e57f23aa"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3445),
                            OrderNumber = "Order number 30",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("66fdb037-8224-47e3-83c2-aa89dbe3b707"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3447),
                            OrderNumber = "Order number 31",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("28b684f2-7b1c-4ec6-9b95-1af1f658034c"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3449),
                            OrderNumber = "Order number 32",
                            ProviderId = new Guid("59f6586a-3f3d-44fb-a34e-f77024371f84")
                        },
                        new
                        {
                            Id = new Guid("49d32423-9905-4614-b7af-6d0a9f9f7366"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3451),
                            OrderNumber = "Order number 33",
                            ProviderId = new Guid("abf69a2d-f358-48be-9b84-717b53df248c")
                        },
                        new
                        {
                            Id = new Guid("81676e78-0692-4df6-a7a0-52f19b71742c"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3454),
                            OrderNumber = "Order number 34",
                            ProviderId = new Guid("31148c84-057b-4de3-b1f9-31437bb57605")
                        },
                        new
                        {
                            Id = new Guid("5a5baa0c-14ea-4d9d-89fc-6489cdd5164e"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3456),
                            OrderNumber = "Order number 35",
                            ProviderId = new Guid("31148c84-057b-4de3-b1f9-31437bb57605")
                        },
                        new
                        {
                            Id = new Guid("f7abd686-8f5f-460c-89ff-15eb406e0a12"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3459),
                            OrderNumber = "Order number 36",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("63ca1eee-dbbf-4eb7-b69d-a4c839c69046"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3461),
                            OrderNumber = "Order number 37",
                            ProviderId = new Guid("22bca438-c3d3-41c5-a439-90a435d15dfc")
                        },
                        new
                        {
                            Id = new Guid("d005215e-57c4-4ed6-8323-c34f390d9c4d"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3463),
                            OrderNumber = "Order number 38",
                            ProviderId = new Guid("22bca438-c3d3-41c5-a439-90a435d15dfc")
                        },
                        new
                        {
                            Id = new Guid("df73e4fd-a944-4608-b793-db010a16e39a"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3465),
                            OrderNumber = "Order number 39",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("fb83a020-ce8a-4fec-b09f-f9b7747567d8"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3467),
                            OrderNumber = "Order number 40",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("176e1a0e-3068-4615-83bf-8a4c4f77ba75"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3469),
                            OrderNumber = "Order number 41",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("c4c5a2f1-68ff-4109-b4a4-6e6147be043d"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3471),
                            OrderNumber = "Order number 42",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("48d7903f-41e4-431b-96d8-8479d64a6380"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3473),
                            OrderNumber = "Order number 43",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("2fefba6d-702c-4b55-a11d-11b8d1274698"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3476),
                            OrderNumber = "Order number 44",
                            ProviderId = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5")
                        },
                        new
                        {
                            Id = new Guid("a7184a4c-d6ab-4053-a1bd-8eeceab88d21"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3478),
                            OrderNumber = "Order number 45",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("88a4f5a8-a1ac-4f77-a70b-fae71329b6fa"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3480),
                            OrderNumber = "Order number 46",
                            ProviderId = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5")
                        },
                        new
                        {
                            Id = new Guid("d59a0bd8-9eaa-4b1a-bb52-80f566671497"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3482),
                            OrderNumber = "Order number 47",
                            ProviderId = new Guid("b84f0c12-b6e5-4f16-a09a-6197dfd1f55c")
                        },
                        new
                        {
                            Id = new Guid("b77dc246-f818-4772-9601-d79b6107fb64"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3483),
                            OrderNumber = "Order number 48",
                            ProviderId = new Guid("abf69a2d-f358-48be-9b84-717b53df248c")
                        },
                        new
                        {
                            Id = new Guid("a4a44c64-f225-45db-bd36-d02cfd597025"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3485),
                            OrderNumber = "Order number 49",
                            ProviderId = new Guid("31148c84-057b-4de3-b1f9-31437bb57605")
                        },
                        new
                        {
                            Id = new Guid("9774dd2f-e772-4948-82f8-28cefc04bbfa"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3487),
                            OrderNumber = "Order number 50",
                            ProviderId = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5")
                        },
                        new
                        {
                            Id = new Guid("26d90544-1f35-4aea-b667-0e50ea4ff547"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3489),
                            OrderNumber = "Order number 51",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("b5075a9d-7e7d-4aad-83aa-bf9ce30d67a1"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3492),
                            OrderNumber = "Order number 52",
                            ProviderId = new Guid("59f6586a-3f3d-44fb-a34e-f77024371f84")
                        },
                        new
                        {
                            Id = new Guid("314f4dc7-0e70-415f-bf50-867853da93df"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3494),
                            OrderNumber = "Order number 53",
                            ProviderId = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5")
                        },
                        new
                        {
                            Id = new Guid("f5bdffc8-e663-4b83-b7f5-cff9236e18ff"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3495),
                            OrderNumber = "Order number 54",
                            ProviderId = new Guid("22bca438-c3d3-41c5-a439-90a435d15dfc")
                        },
                        new
                        {
                            Id = new Guid("f1415cd4-851e-474c-837f-8b931770a656"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3540),
                            OrderNumber = "Order number 55",
                            ProviderId = new Guid("59f6586a-3f3d-44fb-a34e-f77024371f84")
                        },
                        new
                        {
                            Id = new Guid("0d6af5b0-a045-4285-828b-8803888eae3f"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3542),
                            OrderNumber = "Order number 56",
                            ProviderId = new Guid("59f6586a-3f3d-44fb-a34e-f77024371f84")
                        },
                        new
                        {
                            Id = new Guid("32058e85-307a-45d7-a0cf-565635e5ef61"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3543),
                            OrderNumber = "Order number 57",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("dbb37c88-37fd-4f6c-aa29-9478eb4d57cf"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3546),
                            OrderNumber = "Order number 58",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("8c92f769-2d3b-407d-af29-eb386379b23a"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3548),
                            OrderNumber = "Order number 59",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("5be20cbf-21f2-4ba6-a3ae-55a9e5ffb39b"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3551),
                            OrderNumber = "Order number 60",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("3d42f3ac-5fea-4cb6-9761-485c1964f1dd"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3553),
                            OrderNumber = "Order number 61",
                            ProviderId = new Guid("31148c84-057b-4de3-b1f9-31437bb57605")
                        },
                        new
                        {
                            Id = new Guid("bdc7106f-0056-4fe5-8ddc-76b1f33ca190"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3555),
                            OrderNumber = "Order number 62",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("b450aa68-0ca7-4db0-a0ea-ad62adc9722d"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3557),
                            OrderNumber = "Order number 63",
                            ProviderId = new Guid("abf69a2d-f358-48be-9b84-717b53df248c")
                        },
                        new
                        {
                            Id = new Guid("b64badd1-447f-4dca-a828-26afcad6971a"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3559),
                            OrderNumber = "Order number 64",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("639a70eb-d45b-4dc1-addb-7b35f9770a4e"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3561),
                            OrderNumber = "Order number 65",
                            ProviderId = new Guid("abf69a2d-f358-48be-9b84-717b53df248c")
                        },
                        new
                        {
                            Id = new Guid("01890182-c06c-4974-9ee5-6e6a1b6accf9"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3564),
                            OrderNumber = "Order number 66",
                            ProviderId = new Guid("abf69a2d-f358-48be-9b84-717b53df248c")
                        },
                        new
                        {
                            Id = new Guid("22bf7954-6d69-4199-8d26-83ffcbf7d568"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3566),
                            OrderNumber = "Order number 67",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("d1ba3c65-f697-4bca-b983-16357856f3cf"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3569),
                            OrderNumber = "Order number 68",
                            ProviderId = new Guid("31148c84-057b-4de3-b1f9-31437bb57605")
                        },
                        new
                        {
                            Id = new Guid("0fdf550e-e274-4fbb-9df7-8f3946718392"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3571),
                            OrderNumber = "Order number 69",
                            ProviderId = new Guid("abf69a2d-f358-48be-9b84-717b53df248c")
                        },
                        new
                        {
                            Id = new Guid("405ee9f5-6799-4b28-ac94-d575015af397"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3573),
                            OrderNumber = "Order number 70",
                            ProviderId = new Guid("abf69a2d-f358-48be-9b84-717b53df248c")
                        },
                        new
                        {
                            Id = new Guid("07deb86b-9ad0-4454-8b63-995d753c257d"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3575),
                            OrderNumber = "Order number 71",
                            ProviderId = new Guid("b84f0c12-b6e5-4f16-a09a-6197dfd1f55c")
                        },
                        new
                        {
                            Id = new Guid("cac7bdc9-18c3-449f-b157-8b1c1ec95850"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3576),
                            OrderNumber = "Order number 72",
                            ProviderId = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5")
                        },
                        new
                        {
                            Id = new Guid("c224ff94-0f95-4066-904b-f9b34d132844"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3578),
                            OrderNumber = "Order number 73",
                            ProviderId = new Guid("31148c84-057b-4de3-b1f9-31437bb57605")
                        },
                        new
                        {
                            Id = new Guid("91484d8a-93f5-41b2-81c7-bb4d98f63f75"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3580),
                            OrderNumber = "Order number 74",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("0f6226a0-c100-447a-b321-f455d4ee7029"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3582),
                            OrderNumber = "Order number 75",
                            ProviderId = new Guid("b84f0c12-b6e5-4f16-a09a-6197dfd1f55c")
                        },
                        new
                        {
                            Id = new Guid("d84ffd14-8a54-4a2f-b70c-df81a3a8796d"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3585),
                            OrderNumber = "Order number 76",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("08900692-cd6b-45dd-a424-1ff059e5c921"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3587),
                            OrderNumber = "Order number 77",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("b6095ef2-45f1-4124-9956-c82a8d3b166b"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3589),
                            OrderNumber = "Order number 78",
                            ProviderId = new Guid("b84f0c12-b6e5-4f16-a09a-6197dfd1f55c")
                        },
                        new
                        {
                            Id = new Guid("2c755551-d26f-43d0-9ebb-2b11006145f0"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3591),
                            OrderNumber = "Order number 79",
                            ProviderId = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5")
                        },
                        new
                        {
                            Id = new Guid("7782ccb4-a9de-4dea-a61c-321c76646e29"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3593),
                            OrderNumber = "Order number 80",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("87675b4a-e3d1-4154-a0e8-99e8a8dc21c9"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3594),
                            OrderNumber = "Order number 81",
                            ProviderId = new Guid("31148c84-057b-4de3-b1f9-31437bb57605")
                        },
                        new
                        {
                            Id = new Guid("c2e61215-72c3-49e5-9478-6c970a021af5"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3596),
                            OrderNumber = "Order number 82",
                            ProviderId = new Guid("22bca438-c3d3-41c5-a439-90a435d15dfc")
                        },
                        new
                        {
                            Id = new Guid("f89a3ccd-f3d6-4384-a98a-a47904c5bef1"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3598),
                            OrderNumber = "Order number 83",
                            ProviderId = new Guid("b84f0c12-b6e5-4f16-a09a-6197dfd1f55c")
                        },
                        new
                        {
                            Id = new Guid("a9648626-e9ed-4d80-9844-186705d7b7a7"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3601),
                            OrderNumber = "Order number 84",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("f0f2a5bd-9b48-4bb8-94b8-9396c21735a9"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3603),
                            OrderNumber = "Order number 85",
                            ProviderId = new Guid("22bca438-c3d3-41c5-a439-90a435d15dfc")
                        },
                        new
                        {
                            Id = new Guid("90d0aabd-4536-49ab-b902-780e865dee7c"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3605),
                            OrderNumber = "Order number 86",
                            ProviderId = new Guid("22bca438-c3d3-41c5-a439-90a435d15dfc")
                        },
                        new
                        {
                            Id = new Guid("7376855b-2f14-4bbc-b209-4b76b2370453"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3607),
                            OrderNumber = "Order number 87",
                            ProviderId = new Guid("b84f0c12-b6e5-4f16-a09a-6197dfd1f55c")
                        },
                        new
                        {
                            Id = new Guid("40d4e899-90cc-4657-878d-d507fa219d4a"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3609),
                            OrderNumber = "Order number 88",
                            ProviderId = new Guid("22bca438-c3d3-41c5-a439-90a435d15dfc")
                        },
                        new
                        {
                            Id = new Guid("190f793e-45b0-4492-bd41-63aceaa52c8a"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3610),
                            OrderNumber = "Order number 89",
                            ProviderId = new Guid("22bca438-c3d3-41c5-a439-90a435d15dfc")
                        },
                        new
                        {
                            Id = new Guid("cc46af6e-1f0d-4419-b896-39446c8f2ead"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3612),
                            OrderNumber = "Order number 90",
                            ProviderId = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5")
                        },
                        new
                        {
                            Id = new Guid("a5aac90f-5ac8-49ca-ae5f-2d61e8a9b71d"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3614),
                            OrderNumber = "Order number 91",
                            ProviderId = new Guid("29afc549-565b-487a-9b3d-724d1072259d")
                        },
                        new
                        {
                            Id = new Guid("756ea9d9-73fe-42d3-9f33-a3500c36c317"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3617),
                            OrderNumber = "Order number 92",
                            ProviderId = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5")
                        },
                        new
                        {
                            Id = new Guid("0ac69bce-4815-4edb-84c7-e99a81b3de1b"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3619),
                            OrderNumber = "Order number 93",
                            ProviderId = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5")
                        },
                        new
                        {
                            Id = new Guid("8fcb66a6-ebe6-4a93-bb05-4aa7e3beb738"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3621),
                            OrderNumber = "Order number 94",
                            ProviderId = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb")
                        },
                        new
                        {
                            Id = new Guid("2aa52600-42f2-47b7-8795-4ebb9bcbbac8"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3658),
                            OrderNumber = "Order number 95",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("74cdbd0a-3815-4754-a3b9-02c06901ca88"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3660),
                            OrderNumber = "Order number 96",
                            ProviderId = new Guid("31148c84-057b-4de3-b1f9-31437bb57605")
                        },
                        new
                        {
                            Id = new Guid("a0552349-b812-486c-8253-06be5d5832ae"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3662),
                            OrderNumber = "Order number 97",
                            ProviderId = new Guid("b84f0c12-b6e5-4f16-a09a-6197dfd1f55c")
                        },
                        new
                        {
                            Id = new Guid("31ec3d9d-ed95-44a9-8fde-6e9d12908890"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3664),
                            OrderNumber = "Order number 98",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("310e1dcd-74d1-44b9-b344-bc8e7fa4948b"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3666),
                            OrderNumber = "Order number 99",
                            ProviderId = new Guid("3d99a289-f66d-449e-b808-4a9d94979830")
                        },
                        new
                        {
                            Id = new Guid("003ce923-ff62-410f-929c-114cee23030a"),
                            OrderDate = new DateTime(2023, 12, 9, 23, 37, 54, 495, DateTimeKind.Local).AddTicks(3669),
                            OrderNumber = "Order number 100",
                            ProviderId = new Guid("22bca438-c3d3-41c5-a439-90a435d15dfc")
                        });
                });

            modelBuilder.Entity("Store.Entities.ProviderRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("ProviderName")
                        .IsUnique()
                        .HasDatabaseName("UQ_Providers_Name");

                    b.ToTable("Providers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c832765a-58c5-4534-8ab0-42966208dbc7"),
                            ProviderName = "Provider name 1"
                        },
                        new
                        {
                            Id = new Guid("29afc549-565b-487a-9b3d-724d1072259d"),
                            ProviderName = "Provider name 2"
                        },
                        new
                        {
                            Id = new Guid("3d99a289-f66d-449e-b808-4a9d94979830"),
                            ProviderName = "Provider name 3"
                        },
                        new
                        {
                            Id = new Guid("b84f0c12-b6e5-4f16-a09a-6197dfd1f55c"),
                            ProviderName = "Provider name 4"
                        },
                        new
                        {
                            Id = new Guid("a50e90a2-2d1b-4448-9865-d21d029800a5"),
                            ProviderName = "Provider name 5"
                        },
                        new
                        {
                            Id = new Guid("31148c84-057b-4de3-b1f9-31437bb57605"),
                            ProviderName = "Provider name 6"
                        },
                        new
                        {
                            Id = new Guid("59f6586a-3f3d-44fb-a34e-f77024371f84"),
                            ProviderName = "Provider name 7"
                        },
                        new
                        {
                            Id = new Guid("22bca438-c3d3-41c5-a439-90a435d15dfc"),
                            ProviderName = "Provider name 8"
                        },
                        new
                        {
                            Id = new Guid("abf69a2d-f358-48be-9b84-717b53df248c"),
                            ProviderName = "Provider name 9"
                        },
                        new
                        {
                            Id = new Guid("603fc2e9-7224-4ab9-8c41-e6ea30f629fb"),
                            ProviderName = "Provider name 10"
                        });
                });

            modelBuilder.Entity("Store.Entities.OrderItemRecord", b =>
                {
                    b.HasOne("Store.Entities.OrderRecord", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("Store.Entities.OrderRecord", b =>
                {
                    b.HasOne("Store.Entities.ProviderRecord", null)
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Store.Entities.ProviderRecord", "Provider")
                        .WithMany("Orders")
                        .HasForeignKey("ProviderId1");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("Store.Entities.OrderRecord", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("Store.Entities.ProviderRecord", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
